<?php

namespace app\modules\parent\controllers;

use app\models\NotificationActionData;
use app\models\Parents;
use app\models\SchoolTeachers;
use app\models\StudentSchool;
use app\models\SubscriptionChildren;
use app\models\Subscriptions;
use app\models\TutorSession;
use app\models\TutorSessionTiming;
use Yii;
use app\components\GenerateLinks;
use app\components\SendEmail;
use app\components\SendSMS;
use app\components\SendWhatsApp;
use app\models\gradely\InviteLog;
use app\models\gradely\TeacherClass;
use app\models\gradely\User;
use app\models\Homeworks;
use app\models\InappNotification;
use app\models\NotificationMessages;
use app\models\NotificationOutLogging;
use app\models\Notifications;
use yii\web\Controller;

/**
 * Default controller for the `parent` module
 */
class DefaultController extends Controller
{

    public $domain;

    public function beforeAction($action)
    {
        $this->domain = Yii::$app->params['domain'];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex(Notifications $model)
    {
        $actionName = $model->action_name;
        $this->$actionName($model);
    }


    private function welcome_parent(Notifications $model)
    {
        $user = User::findOne(['id' => $model->notificationActionDatas[0]->field_value]);

        // For email sending
        if(NotificationOutLogging::find()->where(['notification_id' => $model->id, 'notification_type' => 'email', 'status' => 1])->exists() == false) {

            $emailOutLogging = $model->CreateOutLogging($model, $user->id, 'email');
            $email = SendEmail::widget([
                'template' => "parent/$model->action_name",
                'subject' => 'Welcome to Gradely!',
                'to' => $user->email,
                'data' => ['user' => $user, 'cta' => GenerateLinks::widget([
                    'destination' => $this->domain . '/site/verify-email?token=' . $user->verification_token,
                    'outingID' => $emailOutLogging->id,
                    'long' => true,
                    'notificationID' => $model->id
                ])]
            ]);
            if ($email)
                $model->UpdateOutLogging($emailOutLogging->id);
        }


        /*================================================
                       In-App Notification
        =================================================*/

        if(NotificationOutLogging::find()->where(['notification_id' => $model->id, 'notification_type' => 'app', 'status' => 1])->exists() == false) {

            $notificationLog = $model->CreateOutLogging($model, $user->id, 'app');

            if($notificationLog) {

                /*Saves to in-app-log*/
                $action_id = $model->notificationActionDatas[0]->action_id;

                $notificationMsg = NotificationMessages::find()->where([
                    'type' => 'app',
                    'action_id' => $action_id
                ])->one();

                $message = str_replace('[Parent Name]', $user->lastname .' '. $user->firstname, $notificationMsg->message);

                $inappLog = new InappNotification();
                $inappLog->notification_id = $notificationLog->notification_id;
                $inappLog->out_logging_id = $notificationLog->id;
                $inappLog->user_id = $notificationLog->receiver_id;
                $inappLog->message = $message;
                if($inappLog->save())
                    //Updates the log status to sent
                    $model->UpdateOutLogging($notificationLog->id);
            }
        }

        if (NotificationOutLogging::find()->where(['notification_type' => ['email', 'app'],'status' => 1,'notification_id' => $model->id,])->exists())
            $model->CompleteNotification();
    }

    private function teacher_set_homework_parent(Notifications $notification)
    {

        $teacher_homework = Homeworks::find()->where([
            'id' => $notification->notificationActionDatas[0]->field_value,
            'publish_status' => 1,
            'access_status' => 'active',
        ])->one();


        $student_parents_homework = StudentSchool::find()->where(['class_id' => $teacher_homework->class_id
        ])->all();

        if ($teacher_homework) {

            foreach ($student_parents_homework as $student_parent_homework) {

                $parent = Parents::findOne(['student_id' => $student_parent_homework->student_id]);


                // For email sending
                $emailOutLogging = $notification->CreateOutLogging($notification, $parent->parent_id, 'email');
                $email = SendEmail::widget([
                    'template' => "parent/$notification->action_name",
                    'subject' => " Hello {$parent->parent->firstname} , Homework has been created",
                    'to' => $parent->parent->email,
                    'data' => [
                        'model' => $teacher_homework,
                    ]
                ]);
                if ($email)
                    $notification->UpdateOutLogging($emailOutLogging->id);

                /**================================================
                 * In-App Notification
                 * =================================================*/

                $notificationLog = $notification->CreateOutLogging($notification, $parent->parent_id, 'app');

                if($notificationLog) {

                    //Updates the log status to sent
                    $notification->UpdateOutLogging($notificationLog->id);

                    /*Saves to in-app-log*/
                    $action_id = $notification->action_id;

                $notificationMsg = NotificationMessages::find()->where([
                    'type' => 'app',
                    'action_id' => $action_id
                ])->one();
                $inappMsg = str_replace('[Parent Name]', $parent->parent->lastname, $notificationMsg->message);
                $inappMsg = str_replace('[Title]', $teacher_homework->title, $inappMsg);
                $inappMsg = str_replace('[Ward]', $parent->student->firstname, $inappMsg);
                $inappMsg = str_replace('[Class Name]', $teacher_homework->class->class_name, $inappMsg);
                $inappMsg = str_replace('[Subject]', $teacher_homework->subject->name, $inappMsg);


                    $inappLog = new InappNotification();
                    $inappLog->notification_id = $notificationLog->notification_id;
                    $inappLog->out_logging_id = $notificationLog->id;
                    $inappLog->user_id = $notificationLog->receiver_id;
                    $inappLog->message = $inappMsg;
                    $inappLog->save();
                }
                //For sending SMS
                $smsOutLogging = $notification->CreateOutLogging($notification, $parent->parent_id, 'sms');

                if ($messages = NotificationMessages::findOne(['type' => 'sms', 'action_id' => $action_id])) {

                    $message = str_replace('[Parent Name]', $parent->parent->lastname, $messages->message);
                    $message = str_replace('[Title]', $teacher_homework->title, $message);
                    $message = str_replace('[Ward]', $parent->student->firstname, $message);
                    $message = str_replace('[Class Name]', $teacher_homework->class->class_name, $message);
                    $message = str_replace('[Subject]', $teacher_homework->subject->name, $message);

                    $response = SendSMS::widget(['phone' => $parent->parent->phone, 'message' => $message]);

                    if ($response == 1000)
                        $notification->UpdateOutLogging($smsOutLogging->id);
                }


                /**=====================================
                                 WhatsApp
                  =======================================
                 */
                $whatsAppLog = $notification->CreateOutLogging($notification, $parent->parent_id, 'whatsapp');

                $whatsAppMsg = NotificationMessages::findOne([
                    'type' => 'whatsapp',
                    'action_id' => $action_id,
                ]);

                if ($whatsAppMsg) {

                    $message = str_replace('[Parent Name]', $parent->parent->lastname, $whatsAppMsg->message);
                    $message = str_replace('[Title]', $teacher_homework->title, $message);
                    $message = str_replace('[Ward]', $parent->student->firstname, $message);
                    $message = str_replace('[Class Name]', $teacher_homework->class->class_name, $message);
                    $message = str_replace('[Subject]', $teacher_homework->subject->name, $message);

                    $response = SendWhatsApp::widget([
                        'receiverPhone' => $parent->parent->phone,
                        'receiverMessage' => $message]);

                    if ($response)
                        $notification->UpdateOutLogging($whatsAppLog->id);
                }

                if (NotificationOutLogging::find()->where(['notification_type' => ['whatsapp', 'app', 'sms', 'email']])->exists())
                    $notification->CompleteNotification();
            }

        }
    }

    private function student_invite_parent(Notifications $notification)
    {
        $model = InviteLog::findOne(['id' => $notification->notificationActionDatas[0]->field_value]);

        $user = User::findOne(['email' => $model->receiver_email]);

        // For email sending
       // if(NotificationOutLogging::find()->where(['notification_id' => $notification->id, 'notification_type' => 'email', 'status' => 1])->exists() == false) {

            $emailOutLogging = $notification->CreateOutLogging($notification, $user->id, 'email');
            $email = SendEmail::widget([
                'template' => "student/$notification->action_name",
                'subject' => " Join {$model->sender_type} on Gradely.NG",
                'to' => $model->receiver_email,
                'data' => [
                    'model' => $model,
                    'cta' => GenerateLinks::widget([ //Generates token
                        'destination' => $this->domain . '/signup/parent?token=' . $model->token,
                        'outingID' => $emailOutLogging->id,
                        'long' => true,
                        'notificationID' => $notification->id
                    ])]
            ]);
            if ($email)
                $notification->UpdateOutLogging($emailOutLogging->id);
        //}


        /**================================================
        In-App Notification
        =================================================*/
        //if(NotificationOutLogging::find()->where(['notification_id' => $notification->id, 'notification_type' => 'app', 'status' => 1])->exists() == false) {
            $notificationLog = $notification->CreateOutLogging($notification, $user->id, 'app');

            if($notificationLog) {

                /*Saves to in-app-log*/
                $action_id = $notification->action_id;

                $notificationMsg = NotificationMessages::find()->where([
                    'type' => 'app',
                    'action_id' => $action_id
                ])->one();

                $message = str_replace('[Parent Name]', $user->lastname .' '. $user->firstname, $notificationMsg->message);

                $inappLog = new InappNotification();
                $inappLog->notification_id = $notificationLog->notification_id;
                $inappLog->out_logging_id = $notificationLog->id;
                $inappLog->user_id = $notificationLog->receiver_id;
                $inappLog->message = $message;
                if($inappLog->save())
                    //Updates the log status to sent
                    $notification->UpdateOutLogging($notificationLog->id);
            }
       // }

        //For sending SMS
       // if(NotificationOutLogging::find()->where(['notification_id' => $notification->id, 'notification_type' => 'sms', 'status' => 1])->exists() == false) {
           // echo 'sms zone';die;
            $smsOutLogging = $notification->CreateOutLogging($notification, $user->id, 'sms');

            if ($messages = NotificationMessages::findOne(['type' => 'sms', 'action_id' => $action_id])) {

                $message = str_replace('[Parent Name]', $user->lastname .' '. $user->firstname, $messages->message);

                $response = SendSMS::widget(['phone' => $model->receiver_phone, 'message' => $message .'<br>'. GenerateLinks::widget([
                        'destination' => $this->domain . '/signup/parent?token=' . $model->token,
                        'outingID' => $smsOutLogging->id,
                        'notificationID' => $notification->id
                    ])]);
                if ($response == 1000)
                    $notification->UpdateOutLogging($smsOutLogging->id);
            }
       // }

        /**=====================================
        WhatsApp
        =======================================
         */
        //if(NotificationOutLogging::find()->where(['notification_id' => $notification->id, 'notification_type' => 'whatsapp', 'status' => 1])->exists() == false) {
            $whatsAppLog = $notification->CreateOutLogging($notification, $user->id, 'whatsapp');
            $whatsAppMsg = NotificationMessages::findOne([
                'type' => 'whatsapp',
                'action_id' => $notification->action_id,
            ]);

            $message = str_replace('[Parent Name]', $user->lastname .' '. $user->firstname, $whatsAppMsg->message);

            if ($whatsAppMsg) {

                $response = SendWhatsApp::widget([
                    'receiverPhone' => $model->receiver_phone,
                    'receiverMessage' => $message .'<br>'. GenerateLinks::widget([
                            'destination' => $this->domain . '/signup/parent?token=' . $model->token,
                            'outingID' => $whatsAppLog->id,
                            'notificationID' => $model->id
                        ])]);
                if ($response)
                    $notification->UpdateOutLogging($whatsAppLog->id);
           // }
        }

        if (NotificationOutLogging::find()->where(['notification_type' => ['email', 'app', 'sms', 'whatsapp']])->exists())
            $notification->CompleteNotification();

    }

    private function homework_done_parent(Notifications $model){

        $homework = Homeworks::findOne([
            'id' => $model->notificationActionDatas[0]->field_value,
            'status' => 1,
            //'student_id' => $student_parent->student_id,
        ]);

        $student_parent = Parents::findOne(['student_id' => $homework->student_id]);

        if($homework){

            // For email sending
            $emailOutLogging = $model->CreateOutLogging($model, $student_parent->id, 'email');
            $email = SendEmail::widget([
                'template' => "parent/$model->action_name",
                'subject' => " Hello {$student_parent->parent->firstname} , Homework completed",
                'to' => $student_parent->parent->email,
                'data' => [
                    'model' => $homework,
                    'parent' => $student_parent,
                ]
            ]);
            if ($email)
                $model->UpdateOutLogging($emailOutLogging->id);

            /**================================================
            In-App Notification
            =================================================*/

            $notificationLog = $model->CreateOutLogging($model, $student_parent->id, 'app');

            if($notificationLog) {
                //Updates the log status to sent
                $model->UpdateOutLogging($notificationLog->id);

//                    /*Saves to in-app-log*/
                $action_id = $model->action_id;

                $notificationMsg = NotificationMessages::find()->where([
                    'type' => 'app',
                    'action_id' => $action_id
                ])->one();

                $inappMsg = str_replace('[Parent Name]', $student_parent->parent->firstname, $notificationMsg->message);
                $inappMsg = str_replace('[Subject Name]', $homework->subject->name, $inappMsg);
                $inappMsg = str_replace('[Student Name]', $student_parent->student->firstname, $inappMsg);


                $inappLog = new InappNotification();
                $inappLog->notification_id = $notificationLog->notification_id;
                $inappLog->out_logging_id = $notificationLog->id;
                $inappLog->user_id = $notificationLog->receiver_id;
                $inappLog->message = $inappMsg;
                $inappLog->save();
            }
            //For sending SMS
            $smsOutLogging = $model->CreateOutLogging($model, $student_parent->id, 'sms');

            if ($messages = NotificationMessages::findOne(['type' => 'sms', 'action_id' => $action_id])) {

                $message = str_replace('[Parent Name]', $student_parent->parent->firstname, $messages->message);
                $message = str_replace('[Subject Name]', $homework->subject->name, $message);
                $message = str_replace('[Student Name]', $student_parent->student->firstname, $message);


                $response = SendSMS::widget(['phone' => $student_parent->parent->phone, 'message' => $message]);

                if ($response == 1000)
                    $model->UpdateOutLogging($smsOutLogging->id);
            }


            /**=====================================
            WhatsApp
            =======================================
             */
            $whatsAppLog = $model->CreateOutLogging($model, $student_parent->id, 'whatsapp');
            $whatsAppMsg = NotificationMessages::findOne([
                'type' => 'whatsapp',
                'action_id' => $action_id,
            ]);

            if ($whatsAppMsg) {

                $message = str_replace('[Parent Name]', $student_parent->parent->firstname, $whatsAppMsg->message);
                $message = str_replace('[Subject Name]', $homework->subject->name, $message);
                $message = str_replace('[Student Name]', $student_parent->student->firstname, $message);

                $response = SendWhatsApp::widget([
                    'receiverPhone' => $student_parent->parent->phone,
                    'receiverMessage' => $message]);

                if ($response)
                    $model->UpdateOutLogging($whatsAppLog->id);
            }
            if (NotificationOutLogging::find()->where(['notification_type' => ['whatsapp', 'app', 'sms', 'email']])->exists())
                $model->CompleteNotification();
        }
    }

    private function payment_made_parent(Notifications $model){

        $subscription_id = $model->notificationActionDatas[0]->field_value;

        $subscription = Subscriptions::findOne(['id' => $subscription_id, 'payment' => 'paid']);

        $subscription_children = SubscriptionChildren::findOne(['subscription_id' => $subscription->id]);

        if($subscription){
            // For email sending
            $emailOutLogging = $model->CreateOutLogging($model, $subscription->user_id, 'email');
            $email = SendEmail::widget([
                'template' => "parent/$model->action_name",
                'subject' => " Hello {$subscription->user->firstname}, Payment made",
                'to' => $subscription->user->email,
                'data' => [
                    'model' => $subscription,
                    'subscriptionDetails' => $subscription_children,
                ]
            ]);
            if ($email)
                $model->UpdateOutLogging($emailOutLogging->id);

            /**================================================
            In-App Notification
            =================================================*/

            $notificationLog = $model->CreateOutLogging($model, $subscription->user_id, 'app');

            if($notificationLog) {
                //Updates the log status to sent
                $model->UpdateOutLogging($notificationLog->id);

                    /*Saves to in-app-log*/
                $action_id = $model->action_id;

                $notificationMsg = NotificationMessages::find()->where([
                    'type' => 'app',
                    'action_id' => $action_id
                ])->one();

                $user = User::findOne($subscription->user_id);

                $inappMsg = str_replace('[Parent Name]', $user->firstname, $notificationMsg->message);

                $inappLog = new InappNotification();
                $inappLog->notification_id = $notificationLog->notification_id;
                $inappLog->out_logging_id = $notificationLog->id;
                $inappLog->user_id = $notificationLog->receiver_id;
                $inappLog->message = $inappMsg;
                $inappLog->save();
            }

            if (NotificationOutLogging::find()->where(['notification_type' => ['email', 'app'],'status' => 1,'notification_id' => $model->id,])->exists())
                $model->CompleteNotification();
        }
    }

    private function parent_add_student_code_parent(Notifications $model){


        $parent = Parents::find()->where(['student_id' => $model->notificationActionDatas[0]->field_value,
        ])->andWhere(['is not', 'code' , null])->one();

        if($parent) {
            // For email sending
            $emailOutLogging = $model->CreateOutLogging($model, $parent->parent_id, 'email');
            $email = SendEmail::widget([
                'template' => "parent/$model->action_name",
                'subject' => " Join {$parent->inviter} on Gradely.NG",
                'to' => $parent->parent->email,
                'data' => [
                    'model' => $parent,
                    'cta' => GenerateLinks::widget([ //Generates token
                        'destination' => $this->domain . '/parents/profile/child?id=' . $parent->student_id,
                        'outingID' => $emailOutLogging->id,
                        'long' => true,
                        'notificationID' => $model->id
                    ])]
            ]);
            if ($email)
                $model->UpdateOutLogging($emailOutLogging->id);


            /**================================================
            In-App Notification
            =================================================*/

            $notificationLog = $model->CreateOutLogging($model, $parent->parent_id, 'app');

            if($notificationLog) {

                /*Saves to in-app-log*/
                $action_id = $model->action_id;

                $notificationMsg = NotificationMessages::find()->where([
                    'type' => 'app',
                    'action_id' => $action_id
                ])->one();

                $inappMsg = str_replace('[Student Name]', $parent->student->firstname, $notificationMsg->message);
                $inappMsg = str_replace('[Parent Name]', $parent->parent->firstname, $inappMsg);

                $inappLog = new InappNotification();
                $inappLog->notification_id = $notificationLog->notification_id;
                $inappLog->out_logging_id = $notificationLog->id;
                $inappLog->user_id = $notificationLog->receiver_id;
                $inappLog->message = $inappMsg;
                if($inappLog->save())
                    //Updates the log status to sent
                    $model->UpdateOutLogging($notificationLog->id);
            }

            //For sending SMS
            $smsOutLogging = $model->CreateOutLogging($model, $parent->parent_id, 'sms');

            if ($messages = NotificationMessages::findOne(['type' => 'sms', 'action_id' => $action_id])) {

                $message = str_replace('[Student Name]', $parent->student->firstname, $messages->message);
                $message = str_replace('[Parent Name]', $parent->parent->firstname, $message);

                $response = SendSMS::widget(['phone' => $parent->parent->phone, 'message' => $message .'<br>'. GenerateLinks::widget([
                        'destination' => $this->domain . '/parents/profile/child?id=' . $parent->student_id,
                        'outingID' => $smsOutLogging->id,
                        'notificationID' => $model->id
                    ])]);
                if ($response == 1000)
                    $model->UpdateOutLogging($smsOutLogging->id);
            }


            /**=====================================
            WhatsApp
            =======================================
             */
            $whatsAppLog = $model->CreateOutLogging($model, $parent->parent_id, 'whatsapp');
            $whatsAppMsg = NotificationMessages::findOne([
                'type' => 'whatsapp',
                'action_id' => $model->action_id,
            ]);

            $message = str_replace('[Student Name]', $parent->student->firstname, $whatsAppMsg->message);
            $message = str_replace('[Parent Name]', $parent->parent->firstname, $message);

            if ($whatsAppMsg) {

                $response = SendWhatsApp::widget([
                    'receiverPhone' => $parent->parent->phone,
                    'receiverMessage' => $message . GenerateLinks::widget([
                            'destination' => $this->domain .'<br>'. '/parents/profile/child?id=' . $parent->student_id,
                            'outingID' => $whatsAppLog->id,
                            'notificationID' => $model->id
                        ])]);
                if ($response)
                    $model->UpdateOutLogging($whatsAppLog->id);
            }

            if (NotificationOutLogging::find()->where(['notification_type' => ['email', 'app', 'sms', 'whatsapp']])->exists())
                $model->CompleteNotification();
        }
        }

    private function teacher_add_student_parent(Notifications $notification){

        $data = NotificationActionData::find()->where(['notification_id' => $notification->id])->one();

        $data_value = json_decode($data->field_value, true);

        $students = $data_value['student_id'];

        $teacher_class = TeacherClass::findOne(['teacher_id' => $data_value['teacher_id']]);

        foreach ($students as $student){

            $parent = Parents::findOne(['student_id' => $student]);


            // For email sending
            if (NotificationOutLogging::find()->where(['notification_id' => $notification->id, 'notification_type' => 'email', 'status' => 1])->exists() == false) {

                $emailOutLogging = $notification->CreateOutLogging($notification, $parent->id, 'email');
                $email = SendEmail::widget([
                    'template' => "student/$notification->action_name",
                    'subject' => 'Welcome to Gradely!:: You have been assigned a Class',
                    'to' => $parent->parent->email,
                    'data' => ['user' => $teacher_class,
                        'dataValue' => $data_value,
                        //'cta' => $this->domain . '/teachers/classes/view-class?class=' . $teacher_class->class_id,
                    ]
                ]);
                if ($email)
                    $notification->UpdateOutLogging($emailOutLogging->id);
            }

            /**================================================
            In-App Notification
            =================================================*/

            $notificationLog = $notification->CreateOutLogging($notification, $parent->id, 'app');

            if($notificationLog) {
                //Updates the log status to sent
                $notification->UpdateOutLogging($notificationLog->id);
                /*Saves to in-app-log*/
                $action_id = $notification->action_id;

                $notificationMsg = NotificationMessages::find()->where([
                    'type' => 'app',
                    'action_id' => $action_id
                ])->one();

                $inappMsg = str_replace('[Parent Name]', $parent->parent->lastname, $notificationMsg->message);
                $inappMsg = str_replace('[Student Name]', $parent->student->lastname, $inappMsg);
                $inappMsg = str_replace('[Class Name]', $teacher_class->class->class_name, $inappMsg);


                $inappLog = new InappNotification();
                $inappLog->notification_id = $notificationLog->notification_id;
                $inappLog->out_logging_id = $notificationLog->id;
                $inappLog->user_id = $notificationLog->receiver_id;
                $inappLog->message = $inappMsg;
                $inappLog->save();
            }

            //For sending SMS
            $smsOutLogging = $notification->CreateOutLogging($notification, $parent->id, 'sms');

            if ($messages = NotificationMessages::findOne(['type' => 'sms', 'action_id' => $action_id])) {

                $message = str_replace('[Parent Name]', $parent->parent->lastname, $messages->message);
                $message = str_replace('[Student Name]', $parent->student->lastname, $message);
                $message = str_replace('[Class Name]', $teacher_class->class->class_name, $message);


                $response = SendSMS::widget(['phone' => $parent->parent->phone, 'message' => $message]);

                if ($response == 1000)
                    $notification->UpdateOutLogging($smsOutLogging->id);
            }

            /**=====================================
             * WhatsApp
             * =======================================
             */
            $whatsAppLog = $notification->CreateOutLogging($notification, $parent->id, 'whatsapp');
            $whatsAppMsg = NotificationMessages::findOne([
                'type' => 'whatsapp',
                'action_id' => $action_id,
            ]);

            if ($whatsAppMsg) {

                $message = str_replace('[Parent Name]', $parent->parent->lastname, $whatsAppMsg->message);
                $message = str_replace('[Student Name]', $parent->student->lastname, $message);
                $message = str_replace('[Class Name]', $teacher_class->class->class_name, $message);

                $response = SendWhatsApp::widget([
                    'receiverPhone' => $parent->parent->phone,
                    'receiverMessage' => $message]);

                if ($response)
                    $notification->UpdateOutLogging($whatsAppLog->id);
            }

            if (NotificationOutLogging::find()->where(['notification_type' => ['whatsapp', 'app', 'email']])->exists())
                $notification->CompleteNotification();
        }

    }

    private function invitation_not_accepted_parent(Notifications $notification){

        $receiver = User::findOne($notification->notificationActionDatas[0]->field_value);

        $parent_invitation = InviteLog::findOne(['receiver_email' => $receiver->email]);

                // For email sending
                $emailOutLogging = $notification->CreateOutLogging($notification, $receiver->id, 'email');
                $email = SendEmail::widget([
                    'template' => "parent/$notification->action_name" . '_' . $notification->notificationActionDatas[1]->field_value,
                    'subject' => " Hello {$receiver->firstname} , Homework has been created",
                    'to' => $receiver->email,
                    'data' => [
                        'model' => $receiver,
                        'cta' => GenerateLinks::widget([ //Generates token
                            'destination' => $this->domain . '/signup/parent?token=' . $parent_invitation->token,
                            'outingID' => $emailOutLogging->id,
                            'long' => true,
                            'notificationID' => $notification->id
                        ])
                    ]
                ]);
                if ($email)
                    $notification->UpdateOutLogging($emailOutLogging->id);
                $action_id = $notification->action_id;

                //For sending SMS
                $smsOutLogging = $notification->CreateOutLogging($notification, $receiver->id, 'sms');

                if ($messages = NotificationMessages::findOne(['type' => 'sms', 'action_id' => $action_id])) {

                    $message = str_replace('[Parent Name]', $receiver->lastname, $messages->message);

                    $response = SendSMS::widget(['phone' => $receiver->phone, 'message' => $message .
                        '<br>'. $this->domain . '/signup/parent?token=' . $parent_invitation->token]);

                    if ($response == 1000)
                        $notification->UpdateOutLogging($smsOutLogging->id);
                }


                /**=====================================
                WhatsApp
                =======================================
                 */
                $whatsAppLog = $notification->CreateOutLogging($notification, $receiver->id, 'whatsapp');

                $whatsAppMsg = NotificationMessages::findOne([
                    'type' => 'whatsapp',
                    'action_id' => $action_id,
                ]);

                if ($whatsAppMsg) {

                    $message = str_replace('[Parent Name]', $receiver->lastname, $whatsAppMsg->message);

                    $response = SendWhatsApp::widget([
                        'receiverPhone' => $receiver->phone,
                        'receiverMessage' => $message .
                            '<br/>'. $this->domain . '/signup/parent?token=' . $parent_invitation->token]);

                    if ($response)
                        $notification->UpdateOutLogging($whatsAppLog->id);
                }

        if (NotificationOutLogging::find()->where(['notification_type' => ['whatsapp', 'app', 'sms', 'email']])->exists())
            $notification->CompleteNotification();

    }

    private function homework_due_date_parent(Notifications $notification){

        $homeworks = Homeworks::find()->where([
            'publish_status' => 1,
            'access_status' => 'active',
            'status' => 0,
        ])->all();


        foreach ($homeworks as $homework) {

            $parent = Parents::findOne(['student_id' => $homework->student_id]);

            if(explode(" ", $homework->close_date)[0]  == (date('Y-m-d', strtotime('+2 days')))) {

                // For email sending
                $emailOutLogging = $notification->CreateOutLoggingHomework($notification, $parent->parent_id, 'email');
                $email = SendEmail::widget([
                    'template' => "parent/$notification->action_name",
                    'subject' => " Hello {$parent->parent->firstname}, Payment made",
                    'to' => $parent->parent->email,
                    'data' => [
                        'model' => $homework,
                        'parent' => $parent,
                    ]
                ]);
                if ($email)
                    $notification->UpdateOutLogging($emailOutLogging->id);

                /**================================================
                In-App Notification
                =================================================*/

                $notificationLog = $notification->CreateOutLoggingHomework($notification, $parent->parent_id, 'app');

                if($notificationLog) {
                    //Updates the log status to sent
                    $notification->UpdateOutLogging($notificationLog->id);

                    /*Saves to in-app-log*/
                    $action_id = $notification->action_id;

                    $notificationMsg = NotificationMessages::find()->where([
                        'type' => 'app',
                        'action_id' => $action_id
                    ])->one();

                    $inappMsg = str_replace('[Parent Name]', $parent->parent->firstname, $notificationMsg->message);

                    $inappLog = new InappNotification();
                    $inappLog->notification_id = $notificationLog->notification_id;
                    $inappLog->out_logging_id = $notificationLog->id;
                    $inappLog->user_id = $notificationLog->receiver_id;
                    $inappLog->message = $inappMsg;
                    $inappLog->save();
                }

                /**=====================================
                WhatsApp
                =======================================
                 */
                $whatsAppLog = $notification->CreateOutLoggingHomework($notification, $parent->parent_id, 'whatsapp');

                $whatsAppMsg = NotificationMessages::findOne([
                    'type' => 'whatsapp',
                    'action_id' => $action_id,
                ]);

                if ($whatsAppMsg) {

                    $message = str_replace('[Parent Name]', $parent->parent->lastname, $whatsAppMsg->message);

                    $response = SendWhatsApp::widget([
                        'receiverPhone' => $parent->parent->phone,
                        'receiverMessage' => $message]);

                    if ($response)
                        $notification->UpdateOutLogging($whatsAppLog->id);
                }
            }
        }

        if (NotificationOutLogging::find()->where(['notification_type' => ['email', 'app', 'whatsapp'],'status' => 1,'notification_id' => $notification->id,])->exists())
            $notification->CompleteNotification();
    }

    private function homework_expired_parent(Notifications $notification){

        $homeworks = Homeworks::find()->where([
            'publish_status' => 1,
            'access_status' => 'active',
            'status' => 1,
        ])->all();


        foreach ($homeworks as $homework) {

            $parent = Parents::findOne(['student_id' => $homework->student_id]);

            if($parent AND (date('Y-m-d H:i:s') == $homework->close_date)) {

                // For email sending
                $emailOutLogging = $notification->CreateOutLoggingHomework($notification, $parent->parent_id, 'email');
                $email = SendEmail::widget([
                    'template' => "parent/$notification->action_name",
                    'subject' => " {$homework->student->firstname}, Homework expires today",
                    'to' => $parent->parent->email,
                    'data' => [
                        'model' => $homework,
                        'parent' => $parent,
                    ]
                ]);
                if ($email)
                    $notification->UpdateOutLogging($emailOutLogging->id);

                /**================================================
                In-App Notification
                =================================================*/

                $notificationLog = $notification->CreateOutLoggingHomework($notification, $parent->parent_id, 'app');

                if($notificationLog) {
                    //Updates the log status to sent
                    $notification->UpdateOutLogging($notificationLog->id);

                    /*Saves to in-app-log*/
                    $action_id = $notification->action_id;

                    $notificationMsg = NotificationMessages::find()->where([
                        'type' => 'app',
                        'action_id' => $action_id
                    ])->one();

                    $inappMsg = str_replace('[Parent Name]', $parent->parent->firstname, $notificationMsg->message);
                    $inappMsg = str_replace('[Student Name]', $homework->student->firstname, $inappMsg);
                    $inappMsg = str_replace('[Title]', $homework->title, $inappMsg);

                    $inappLog = new InappNotification();
                    $inappLog->notification_id = $notificationLog->notification_id;
                    $inappLog->out_logging_id = $notificationLog->id;
                    $inappLog->user_id = $notificationLog->receiver_id;
                    $inappLog->message = $inappMsg;
                    $inappLog->save();
                }

                /**=====================================
                WhatsApp
                =======================================
                 */
                $whatsAppLog = $notification->CreateOutLoggingHomework($notification, $parent->parent_id, 'whatsapp');

                $whatsAppMsg = NotificationMessages::findOne([
                    'type' => 'whatsapp',
                    'action_id' => $action_id,
                ]);

                if ($whatsAppMsg) {

                    $message = str_replace('[Parent Name]', $parent->parent->lastname, $whatsAppMsg->message);
                    $message = str_replace('[Student Name]', $homework->student->firstname, $message);
                    $message = str_replace('[Title]', $homework->title, $message);

                    $response = SendWhatsApp::widget([
                        'receiverPhone' => $parent->parent->phone,
                        'receiverMessage' => $message]);

                    if ($response)
                        $notification->UpdateOutLogging($whatsAppLog->id);
                }
            }
        }

        if (NotificationOutLogging::find()->where(['notification_type' => ['email', 'app', 'whatsapp'],'status' => 1,'notification_id' => $notification->id,])->exists())
            $notification->CompleteNotification();
    }

    private function tutor_session_ended_parent(Notifications $notification){

        $session_id = $notification->notificationActionDatas[0];

        $session_tutor = TutorSession::findOne($session_id);

        if($session_tutor->status == 'completed') {

            $parent = Parents::findOne(['student_id' => $session_tutor->student_id]);

            // For email sending
            $emailOutLogging = $notification->CreateOutLogging($notification, $parent->parent_id, 'email');
            $email = SendEmail::widget([
                'template' => "student/$notification->action_name",
                'subject' => "{$session_tutor->title}, has ended!",
                'to' => $parent->parent->email,
                'data' => [
                    'model' => $session_tutor,
                    'parent' => $parent,
//                'cta' => GenerateLinks::widget([ //Generates token
//                    'destination' => $this->domain . '/students/homework/completed',
//                    'outingID' => $emailOutLogging->id,
//                    'long' => true,
//                    'notificationID' => $notification->id
//                ])
                ]
            ]);
            if ($email)
                $notification->UpdateOutLogging($emailOutLogging->id);

            /**================================================
            In-App Notification
            =================================================*/

            $notificationLog = $notification->CreateOutLogging($notification, $parent->parent_id, 'app');

            if($notificationLog) {
                //Updates the log status to sent
                $notification->UpdateOutLogging($notificationLog->id);

                /*Saves to in-app-log*/
                $action_id = $notification->action_id;

                $notificationMsg = NotificationMessages::find()->where([
                    'type' => 'app',
                    'action_id' => $action_id
                ])->one();

                $inappMsg = str_replace('[Parent Name]', $parent->parent->firstname, $notificationMsg->message);

                $inappLog = new InappNotification();
                $inappLog->notification_id = $notificationLog->notification_id;
                $inappLog->out_logging_id = $notificationLog->id;
                $inappLog->user_id = $notificationLog->receiver_id;
                $inappLog->message = $inappMsg;
                $inappLog->save();
            }

            /**=====================================
             * WhatsApp
             * =======================================
             */
            $whatsAppLog = $notification->CreateOutLogging($notification, $parent->parent_id, 'whatsapp');
            $whatsAppMsg = NotificationMessages::findOne([
                'type' => 'whatsapp',
                'action_id' => $action_id,
            ]);

            if ($whatsAppMsg) {

                $message = str_replace('[Parent Name]', $parent->parent->lastname, $whatsAppMsg->message);

                $response = SendWhatsApp::widget([
                    'receiverPhone' => $parent->parent->phone,
                    'receiverMessage' => $message]);

                if ($response)
                    $notification->UpdateOutLogging($whatsAppLog->id);
            }

            if (NotificationOutLogging::find()->where(['notification_type' => ['email', 'app', 'whatsapp'],'status' => 1,'notification_id' => $notification->id,])->exists())
                $notification->CompleteNotification();
        }
    }

    private function tutor_session_parent(Notifications $notification){

        $sessions_tutor = TutorSession::find()->where([
            'category' => 'class',
            'is_school' => 1,
        ])->all();

        foreach ($sessions_tutor as $session_tutor){

            $student = StudentSchool::findOne(['student_id' => $session_tutor->student_id]);

            $parent = Parents::findOne(['student_id' => $student->student_id]);

            if($parent AND explode(' ', $session_tutor->availability)[0] == date('Y-m-d') AND explode(' ', $session_tutor->availability)[1] > date('H:i:s', strtotime('-10 minutes')) ){

                // For email sending
                $emailOutLogging = $notification->CreateOutLogging($notification, $parent->parent_id, 'email');
                $email = SendEmail::widget([
                    'template' => "parent/$notification->action_name",
                    'subject' => "{$session_tutor->title}, has ended!",
                    'to' => $parent->parent->email,
                    'data' => [
                        'model' => $session_tutor,
                        'parent' => $parent,
//                'cta' => GenerateLinks::widget([ //Generates token
//                    'destination' => $this->domain . '/students/homework/completed',
//                    'outingID' => $emailOutLogging->id,
//                    'long' => true,
//                    'notificationID' => $notification->id
//                ])
                    ]
                ]);
                if ($email)
                    $notification->UpdateOutLogging($emailOutLogging->id);

                /**================================================
                In-App Notification
                =================================================*/

                $notificationLog = $notification->CreateOutLogging($notification, $parent->parent_id, 'app');

                if($notificationLog) {
                    //Updates the log status to sent
                    $notification->UpdateOutLogging($notificationLog->id);

                    /*Saves to in-app-log*/
                    $action_id = $notification->action_id;

                    $notificationMsg = NotificationMessages::find()->where([
                        'type' => 'app',
                        'action_id' => $action_id
                    ])->one();

                    $inappMsg = str_replace('[Parent Name]', $parent->parent->firstname, $notificationMsg->message);

                    $inappLog = new InappNotification();
                    $inappLog->notification_id = $notificationLog->notification_id;
                    $inappLog->out_logging_id = $notificationLog->id;
                    $inappLog->user_id = $notificationLog->receiver_id;
                    $inappLog->message = $inappMsg;
                    $inappLog->save();
                }

                /**=====================================
                 * WhatsApp
                 * =======================================
                 */
                $whatsAppLog = $notification->CreateOutLogging($notification, $parent->parent_id, 'whatsapp');
                $whatsAppMsg = NotificationMessages::findOne([
                    'type' => 'whatsapp',
                    'action_id' => $action_id,
                ]);

                if ($whatsAppMsg) {

                    $message = str_replace('[Parent Name]', $parent->parent->lastname, $whatsAppMsg->message);

                    $response = SendWhatsApp::widget([
                        'receiverPhone' => $parent->parent->phone,
                        'receiverMessage' => $message]);

                    if ($response)
                        $notification->UpdateOutLogging($whatsAppLog->id);
                }

                if (NotificationOutLogging::find()->where(['notification_type' => ['email', 'app', 'whatsapp'],'status' => 1,'notification_id' => $notification->id,])->exists())
                    $notification->CompleteNotification();
            }


            }
        }

}
