version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/test/tapi.gradely.ng
hooks:
#  BeforeInstall:
#    - location: vagrant/scripts/install_dependencies.sh
#      timeout: 300
#      runas: root
  ValidateService:
    - location: vagrant/scripts/composer_install.sh
      timeout: 300
      runas: root